# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "ata_piix" "ohci_pci" "ehci_pci" "sd_mod" "sr_mod" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { label = "root";
      fsType = "btrfs";
      options = ["noatime" "autodefrag" "compress=lzo" "space_cache"];
    };

  fileSystems."/boot" =
    { label = "boot";
      fsType = "ext2";
    };

  swapDevices = [
    { label = "s0"; }
  ];

  nix.maxJobs = lib.mkDefault 1;
  virtualisation.virtualbox.guest.enable = true;
}
