# This file was generated by go2nix.
{ stdenv, buildGoPackage, fetchFromGitHub }:

buildGoPackage rec {
  name = "rocker-${version}";
  #version = "1.2.0-${stdenv.lib.strings.substring 0 7 rev}";
  version = "1.2.0";
  rev = "${version}";

  goPackagePath = "github.com/grammarly/rocker";

  src = fetchFromGitHub {
    inherit rev;
    owner = "grammarly";
    repo = "rocker";
    sha256 = "18xqz0x86hj59fxvcabsk6g558m3f9qa2isid16a5p4crifzxb9c";
    #sha256 = "0vksqncrkf00fzsrsbgs0xlk7kwajxpgsfz0z2nm102rj5xz04hg";
  };

  #goDeps = ./deps.json;
}
